
language: haskell

addons:
    apt:
        packages:
            - libssh2-1-dev
            - libssh2-1

matrix:
    include:
        - ghc: 7.6
        # There is a weird problem with the linker on ghc-7.8 and ghc-7.10.
        # that makes test/EmbedTree.hs not be able to be linked with ld,
        # possibly because it is using Template Haskell?
        # - ghc: 7.8

install:
    - cabal update
    - cabal install cabal-install
    - export PATH="$HOME/.cabal/bin:$PATH"
    # c2hs uses the library language-c, which needs a recent version of
    # happy and alex to install.
    - cabal install happy alex
    - cabal install c2hs
    - cabal install --only-dependencies --enable-tests --force-reinstalls

script:
    - cabal configure --enable-tests
    - cabal build

    # There is a weird problem on 7.6 where the tests sometimes randomly
    # fail.  The exception BANNER_RECV seems to be thrown randomly...?
    # - cabal test
