flags: {}
packages:
- '.'

# For ghc-7.8
# extra-deps:
#     - RSA-1.2.2.0
#     - SimpleAES-0.4.2
#     - libssh2-0.2.0.3
#     - th-lift-instances-0.1.5
# resolver: lts-2.13

# For ghc-7.10
extra-deps:
    - RSA-1.2.2.0
    - SimpleAES-0.4.2
    - libssh2-0.2.0.3
    - th-lift-instances-0.1.5
resolver: nightly-2015-06-17
